module.exports = {
  preset: 'jest-expo',
  setupFiles: ['<rootDir>/jest.env.js'],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  testEnvironment: 'jsdom',
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': 'babel-jest',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  testMatch: [
    '<rootDir>/app/(tabs)/__tests__/**/*.test.(ts|tsx|js|jsx)',
    '<rootDir>/app/(auth)/__tests__/**/*.test.(ts|tsx|js|jsx)',
    '<rootDir>/Context/__tests__/**/*.test.(ts|tsx|js|jsx)',
  ],
  collectCoverageFrom: [
    '<rootDir>/app/**/utils/**/*.{ts,tsx}',
    '!<rootDir>/app/**/__tests__/**',
    '<rootDir>/app/(tabs)/**/*.(ts|tsx)',
    '<rootDir>/app/(auth)/**/*.(ts|tsx)',
    '<rootDir>/Context/**/*.(ts|tsx)',
    '<rootDir>/components/**/*.{ts,tsx}',
    '<rootDir>/store/**/*.{ts,tsx}',
    '<rootDir>/constants/**/*.{ts,tsx}',
    '<rootDir>/src/**/*.{ts,tsx}',
    '<rootDir>/*.{ts,tsx}',
    '!<rootDir>/app/(tabs)/__tests__/**',
    '!<rootDir>/app/(auth)/__tests__/**',
    '!<rootDir>/Context/__tests__/**',
    '!<rootDir>/components/**/__tests__/**',
    '!<rootDir>/components/**/*.test.{ts,tsx}',
    '!<rootDir>/components/**/*.web.{ts,tsx}',
    '!<rootDir>/app.config.ts',
    '!<rootDir>/node_modules/**',
  ],
  coverageThreshold: {
    global: {
      branches: 5,
      functions: 5,
      lines: 5,
      statements: 5,
    },
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
  },
};
